name: ESFS_Env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.14
  - numpy=1.26.4
  - scipy=1.11.4
  - pandas=2.2.3
  - matplotlib=3.7.3
  - scikit-learn=1.5.2
  - umap-learn=0.5.7
  - multiprocess=0.70.18
  - p-tqdm=1.4.2
  - anndata=0.11.4
  - plotly=6.5.0
  - scanpy=1.11.1
  - ipywidgets=8.1.8
  - notebook=7.5.0
  - jupyterlab=4.5.0
  - python-igraph=1.0.0
  - leidenalg=0.11.0
  - fastcluster=1.3.0
  - pip
  - pip:
      - -e .
